name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip
    # Package depends
  - numpy
  - matplotlib
  - networkx
  - scipy

    # Pip-only installs
  - pip:
     - sphinx-autoapi

